### ISSUE TITLE
Mark traits

### ISSUE THREAD

**Issue by Xela00** [Xela00/PyTFall#46]
- Not all traits are marked, making it hard to work with them.

On the next major traits review, you should make sure that every trait group can be distinguished from another.

We have some markers like:

Breasts = True
Body = True
Type = "permanent" # Redundant, we determine this by other flags # Not used in the game.
Basetrait = True
Mobs_only = True
Elemental = True
Personality = True
Races = True

However traits in skills file, in modifications, in training and last four traits in body (they don't really fit well anywhere :( , maybe a tag like other = true will do).

This is not a priority, I'll just use whatever is tagged for now but more control would be nice to have.

**Comment by DarkTl** [comment]
This is because remaining traits don't have any specific, complex, unusual logic behind them. Ie they are not permanent, or mandatory, or something else. I suppose I can tag them as other=true if you think it will help somehow.

**Comment by Xela00** [comment]
Try to come up with something... we need this, *other* for all of these traits *cannot* be the best we can do.

**Comment by Xela00** [comment]
By the way, also a client = True for traits that you believe a client could like in an employee would be great, for now I'll just use body-types and breasts.

**Comment by DarkTl** [comment]
No, it's wrong. Body means constitution. Just like with breasts, a character cannot to not have a constitution (manly, lolita, etc).
Thus, strange eyes is a permanent trait, but it's not mandatory like constitution, thus it's not a body trait.
Thus Type = "permanent" is NOT redundant. Such traits cannot be removed, because are tied to pictures.

**Comment by DarkTl** [comment]
To summarize:
"client": true added where makes sense in my opinion
"permanent": true (instead of former Type = "permanent") means appearance traits that cannot be removed cause tied to pictures or dna.
"virginity": true for virgin and MILF. Unique cases.
"sexual": true for all traits that are related to sex. From sexy air to lesbian.
"character_trait": true for all others. It's minor traits that might even have checks here and there, but not very important and can be gained and removed anytime, if you have a proper item or something.
